board/urls.py
# blog/urls.py
from django.urls import path
from board import views

app_name = 'board'
urlpatterns = [
    path('', views.board_list, name='list'),
    path('detail/<int:board_id>/', views.board_detail, name='detail'),
    path('delete/', views.board_delete, name='delte'),
    path('write/', views.board_write, name='write'),
    path('modify/<int:board_id>/', views.board_modify_get, name='modify_get'),
    path('modify/', views.board_modify_post, name='modify_post'),
    path('comment/wrtie/', views.comment_write, name='comment-write'),
    path('comment/delete/', views.comment_delete, name='comment-delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

def index(request):
    return render(request,'index.html')

urlpatterns = [
    path('',index),
    path('admin/', admin.site.urls),
    path('chatgpt/',include('chatgpt.urls')),
    path('signlanguagetochatgpt/',include('signlanguagetochatgpt.urls')),
    path('kakao_login/',include('kakao_login.urls')),
    path('board/',include('board.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from kakao_login.models import Users


class Board(models.Model):
    board_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    body = models.TextField()
    created_datetime = models.DateTimeField(auto_now_add=True)
    modified_datetime = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)
    
    
class Comment(models.Model):
    comment_id = models.AutoField(primary_key=True)
    comment_content = models.CharField(max_length=100)
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    created_datetime = models.DateTimeField(auto_now_add=True)
    modified_datetime = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from board import models
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
import json
from django.conf import settings

kakao_login_url = settings.SOCIALACCOUNT_PROVIDERS['kakao']['APP']['login_url']


# 게시글 목록
def board_list(request):
    # 게시판 리스트 가져오기 (is_deleted가 True인 것 제외)
    posts = models.Board.objects.select_related("user").exclude(is_deleted=True).order_by('-created_datetime').all()

    # 페이지 처리
    page = request.GET.get("page", 1) # 기본값 1
    paginator = Paginator(posts, 10) # 한 페이지에 보여질 게시물 수를 10개로 설정
    
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    return render(request, "board/list.html", {"posts": posts})


# 게시글 상세
def board_detail(request, board_id):
    post = get_object_or_404(models.Board, board_id=board_id)
    comments = models.Comment.objects.filter(board=post, is_deleted=False).select_related("user").order_by('created_datetime').all()
    return render(request, "board/detail.html", {"post": post, "comments": comments, "cur_page": request.GET.get("page", 1)})


# 게시글 삭제
@require_POST
def board_delete(request):
    json_data = json.loads(request.body.decode('utf-8'))
    board_id = json_data.get('board_id') 
    post = get_object_or_404(models.Board, board_id=board_id)
    
    if str(request.session.get("user_id", None)) == post.user.user_id:
        post.is_deleted = True
        post.save()
        data = {"message": "게시글을 삭제하였습니다.", "icon": "success"}
    else:
        data = {"message": "작성자만 삭제할 수 있습니다.", "icon": "error"}
         
    return JsonResponse(data)


# 게시글 작성
def board_write(request):
    if request.method == "POST":
        # 유저 정보 불러오기
        session_user_id = request.session.get("user_id", None)
        if session_user_id is None: # 로그인 페이지로
            return redirect(kakao_login_url)
        if models.Users.objects.filter(user_id=session_user_id).exists():
            user = models.Users.objects.get(user_id=session_user_id)
            
        # 게시글 작성 로직
        post = models.Board.objects.create(
            user = user,
            title = request.POST.get("title"),
            body = request.POST.get("body")
        )
        return redirect("/board/detail/" + str(post.board_id) + "/")
    else:
        # 게시글 작성 페이지로 이동
        context = {
            "cur_page": request.GET.get("page", 1),
            "type": "write"
        }
        return render(request, "board/write.html", context)
    
    
# 게시글 수정 - GET
def board_modify_get(request, board_id):
    post = models.Board.objects.get(board_id=board_id)
    context = {
        "cur_page": request.GET.get("page", 1),
        "post": post,
        "type": "modify"
    }
    return render(request, "board/write.html", context)


# 게시글 수정 - POST
@require_POST
def board_modify_post(request):
    json_data = json.loads(request.body.decode('utf-8'))
    board_id = json_data.get('board_id')
    post = get_object_or_404(models.Board, board_id=board_id)
    
    if str(request.session.get("user_id", None)) == post.user.user_id:
        post.title = json_data.get('title')
        post.body = json_data.get('body')
        post.save()
        data = {"message": "게시글을 수정하였습니다.", "icon": "success"}
    else:
        data = {"message": "작성자만 수정할 수 있습니다.", "icon": "error"}
 
    return JsonResponse(data)
    

# 댓글 작성   
@require_POST
def comment_write(request):
    # 유저 정보 불러오기
    session_user_id = request.session.get("user_id", None)
    if session_user_id is None: # 로그인 페이지로
        return redirect(kakao_login_url)
    if models.Users.objects.filter(user_id=session_user_id).exists():
        user = models.Users.objects.get(user_id=session_user_id)
    
    board_id = request.POST.get("board_id")
    cur_page = request.POST.get("cur_page", 1)
    
    # 댓글 작성 로직
    comment = models.Comment.objects.create(
        user = user,
        board = models.Board.objects.get(board_id=board_id),
        comment_content = request.POST.get("comment_content")
    )
    return redirect("/board/detail/" + str(board_id) + "/?page=" + cur_page)


# 댓글 삭제
@require_POST
def comment_delete(request):
    json_data = json.loads(request.body.decode('utf-8'))
    comment_id = json_data.get('comment_id') 
    comment = get_object_or_404(models.Comment, comment_id=comment_id)
    
    if str(request.session.get("user_id", None)) == comment.user.user_id:
        comment.is_deleted = True
        comment.save()
        data = {"message": "댓글을 삭제하였습니다.", "icon": "success"}
    else:
        data = {"message": "작성자만 삭제할 수 있습니다.", "icon": "error"}
         
    return JsonResponse(data)

board/templates/board/detail.html
{% extends 'base.html' %}

{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'board/common.css' %}">
<link rel="stylesheet" href="{% static 'board/detail_style.css' %}">
<script src="{% static 'board/js/detail.js' %}" defer></script>
{% endblock %}

{% block content %}
<div class="hero text-center text-white main">
    <div>
        <h2 class="display-6 mt-3">자유 게시판</h2>
        
        <div class="description mb-2">
            <p class="lead m-0" style="text-align: left;">
                1. 커뮤니티 매너를 지켜 즐겁게 소통하며, 자유게시판을 적절하게 이용해 주세요.<br/>
                2. 비회원은 글이나 댓글 작성이 불가능하며, 조회만 가능합니다.
            </p>
        </div>

        <div><a class="btn btn-primary mt-2 write_btn" href="/board/write/?page={{ cur_page }}" style="float:right;">새로운 글 작성</a></div>

        <div class="post-content">
            <h2>{{ post.title }}</h2>
            <p style="white-space: pre-line;">{{ post.body }}</p>
            <p>작성자: {{ post.user.user_name }}</p>
            <p>작성일시: {{ post.created_datetime }}</p>
            
            <div class="my-4">
                <a href="/board/?page={{ cur_page }}" class="btn btn-primary" style="margin-right: 5px;">목록</a>
                <a href="/board/modify/{{ post.board_id }}/?page={{ cur_page }}" class="btn btn-primary" style="margin: 0 5px;">수정</a>
                <button onclick="del_post({{ post.board_id }}, {{ cur_page }})" class="btn btn-danger" style="margin-left: 5px;">삭제</button>
            </div>
        </div>
        <hr/>


        <div class="comment-form">
            <form action="{% url 'board:comment-write' %}" method="post">
                {% csrf_token %}
                <input name="board_id" value="{{ post.board_id }}" hidden />
                <input name="cur_page" value="{{ cur_page }}" hidden />
                <textarea name="comment_content" id="comment_content" rows="3" placeholder="댓글을 입력하세요" maxlength="100" required></textarea>
                <button type="submit" id="form-submit" class="btn btn-primary comment-btn">댓글 작성</button>
            </form>
        </div>


        
        {% for comment in comments %}
            <div class="comment">
                <span style="color:black;">{{ comment.comment_content }} | {{ comment.created_datetime }} | 작성자: {{ comment.user.user_name }}</span>
                <a onClick="commnt_del('{{ comment.comment_id }}')" title="삭제" class="btn del-btn ml-3">
                    <span class="material-icons close-icon">close</span>
                </a>
            </div>
        {% endfor %}
        

    </div>
</div>
{% endblock %}

board/templates/board/list.html
{% extends 'base.html' %}

{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'board/common.css' %}">
<link rel="stylesheet" href="{% static 'board/style.css' %}">
{% endblock %}

{% block content %}
<div class="hero text-center text-white main">
    <div>
        <h2 class="display-6 mt-3">자유 게시판</h2>
        
        <div class="description mb-2">
            <p class="lead m-0" style="text-align: left;">
                1. 커뮤니티 매너를 지켜 즐겁게 소통하며, 자유게시판을 적절하게 이용해 주세요.<br/>
                2. 비회원은 글이나 댓글 작성이 불가능하며, 조회만 가능합니다.
            </p>
        </div>

        <div><a class="btn btn-primary mt-2 write_btn" href="/board/write/?page={{ posts.number }}" style="float:right;">새로운 글 작성</a></div>

        <table class="table mt-4">
            <thead>
                <tr>
                  <th scope="col">제목</th>
                  <th scope="col">작성자</th>
                  <th scope="col">작성일시</th>
                </tr>
            </thead>

            <tbody class="table-group-divider">
                {% for post in posts %}
                    <tr onclick="window.location.href='/board/detail/{{ post.board_id }}/?page={{ posts.number }}'" class="raw-data">
                        <td style="font-weight: bold;">{{ post.title }}</td>
                        <td>{{ post.user.user_name }}</td>
                        <td>{{ post.created_datetime }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ posts.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ posts.number }} of {{ posts.paginator.num_pages }}
                </span>

                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}">next</a>
                    <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>

    </div>
</div>
{% endblock %}

board/templates/board/write.html
{% extends 'base.html' %}

{% load static %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'board/common.css' %}">
<link rel="stylesheet" href="{% static 'board/write.css' %}">
<script src="{% static 'board/js/modify.js' %}" defer></script>
{% endblock %}

{% block content %}
<div class="hero text-center text-white main">
    <div>
        <h2 class="display-6 mt-3">자유 게시판</h2>
        
        <div class="description mb-2">
            <p class="lead m-0" style="text-align: left;">
                1. 커뮤니티 매너를 지켜 즐겁게 소통하며, 자유게시판을 적절하게 이용해 주세요.<br/>
                2. 비회원은 글이나 댓글 작성이 불가능하며, 조회만 가능합니다.
            </p>
        </div>

        {% if type == "write" %}
            <form action="{% url 'board:write' %}" method="post">
        {% else %}
            <form action="{% url 'board:modify_post' %}" method="post">   
        {% endif %}
                {% csrf_token %}
                <label for="title">제목</label>
                <input type="text" id="title" name="title" maxlength="50" value="{{ post.title }}" required>
                <br>
            
                <label for="body">내용</label>
                <textarea id="body" name="body" rows="4" required>{{ post.body }}</textarea>
                <br>
                
                <div class="my-4">
                    <a href="/board/?page={{ cur_page }}" class="btn btn-primary" style="margin-right: 5px;">목록</a>
                    <button {% if type == "write" %}type="submit"{% else %}type="button" onClick="board_modify('{{ post.board_id }}', '{{ cur_page }}')"{% endif %} class="btn btn-primary" style="margin-left:5px;">{% if type == "write" %}작성{% else %}수정{% endif %}</button>
                </div>
            </form>


    </div>
</div>
{% endblock %}